Document: offsite-cert
Title: Debian offsite-cert Manual
Author: <insert document author here>
Abstract: This manual describes what offsite-cert is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/offsite-cert/offsite-cert.sgml.gz

Format: postscript
Files: /usr/share/doc/offsite-cert/offsite-cert.ps.gz

Format: text
Files: /usr/share/doc/offsite-cert/offsite-cert.text.gz

Format: HTML
Index: /usr/share/doc/offsite-cert/html/index.html
Files: /usr/share/doc/offsite-cert/html/*.html
